apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: grafana
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
      app: grafana
  template:
    metadata: 
      name: grafana
      labels: 
        app: grafana
    spec:
      containers:
        - name: grafana-container
          image: grafana/grafana
          ports:
          - containerPort: 3000