apiVersion: v1 
kind: Service
metadata:
  name: apache-service
  namespace: {{ .Values.namespace }}
  labels:
    app: myweb
    tier: frontend
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      nodePort: {{ .Values.nodePort }}