apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  namespace: {{ .Values.namespace }}
  labels:
    app: myweb
    tier: frontend
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
      app: myweb
  template:
    metadata: 
      name: mywebapp
      labels: 
        app: myweb
    spec:
      containers:
      - name: mywebapp-container
        image: jaladeesh/web-application:v1
        ports:
        - containerPort: 8080