apiVersion: apps/v1
kind: Deployment
metadata:
  name: prome-deploy
  namespace: {{ .Values.namespace }}
  labels:
    app: prometheus
spec:
  replicas: {{ .Values.replicas }}
  selector: 
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels: 
        app: prometheus
    spec:
      volumes:
        - name: prometheus-config-volume
          configMap:
            name: prometheus-config
            items:
              - key: prometheus.yml
                path: prometheus.yml
      containers:
        - name: prometheus-container
          image: prom/prometheus:v2.42.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus
