apiVersion: v1 
kind: Service
metadata:
  name: prometheus-service
  namespace: {{ .Values.namespace}}
  labels:
    app: prometheus
spec:
  type: NodePort
  selector:
    app: prometheus
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: {{ .Values.nodePort }}
