apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-deployment
  labels:
    app: myweb
    tier: frontend
spec:
  replicas: 2
  selector: 
    matchLabels:
      app: myweb
  template:
    metadata: 
      name: mywebapp
      labels: 
        app: myweb
    spec:
      containers:
      - name: mywebapp-container
        image: jaladeesh/mywebapp:v1
        ports:
        - containerPort: 8080

---
apiVersion: v1 
kind: Service
metadata:
  name: apache-service
  labels:
    app: myweb
    tier: frontend
spec:
  type: NodePort
  selector:
    app: myweb
  ports:
    - name: http-metrics
      port: 8080
      targetPort: 8080
      nodePort: 30009
